name: Java CI with Gradle using composite action

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ralfstuckert/composite-action@main
      id: composite
    - run: echo ${{ steps.composite.outputs.jar-version }}
